### ISSUE TITLE
Not an issue but

### ISSUE THREAD

**Issue by ChooMcoo** [AudioKnight/Starlancer#1]
I was hoping you'd be willing to join the Lethal Company Modding discord! There's tons of people in there and a forum area where you can post your mod and directly talk with people about it. There's multiple other custom moon mod devs including the guy in charge of Lethal Expansion and they're always very willing to help with various issues! I also find it to be a very convenient way to keep up with my favorite mods and upon landing I can already tell I'm gonna love this one. Here's the invite link if you're interested: https://discord.com/invite/lcmod

**Comment by AudioKnight** [comment]
I actually had already joined, but I appreciate you reaching out to me! I sorta crunched to get the moon out before I go out of town for the weekend, but I'll be continuing development next week and possibly reach out to the modding community.

Glad you're liking the aesthetic thus far!
