### ISSUE TITLE
Particle System Spam

### ISSUE THREAD

**Issue by VanilaBOI** [AudioKnight/Starlancer#10]
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Info   :MaskTheDead] Something is leaving the mask range, i have 0 body nearby!
[Info   :MaskTheDead] Collided with HoarderBugModel (UnityEngine.GameObject)
[Info   :MaskTheDead] This is not a bone!
[Info   :MaskTheDead] The collider leaving is not of a ragdoll
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Info   :ReservedItemSlotCore-1.8.12] 000
[Info   :ReservedItemSlotCore-1.8.12] 111
[Info   :ReservedItemSlotCore-1.8.12] RESULT: 1 222
[Warning: Unity Log] PlayOneShot was called with a null AudioClip.
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Info   :RugbugRedfern.SkinwalkerMod] IsEnemyEnabled ForestGiant(Clone) False
[Info   :RugbugRedfern.SkinwalkerMod] IsEnemyEnabled ForestGiant(Clone) False
[Info   :RugbugRedfern.SkinwalkerMod] IsEnemyEnabled HoarderBug(Clone)(Clone) False
[Info   :RugbugRedfern.SkinwalkerMod] IsEnemyEnabled Centipede(Clone)(Clone) False
[Info   :RugbugRedfern.SkinwalkerMod] IsEnemyEnabled ForestGiant(Clone) False
[Info   :RugbugRedfern.SkinwalkerMod] IsEnemyEnabled BaboonHawkEnemy(Clone) False
[Info   :RugbugRedfern.SkinwalkerMod] IsEnemyEnabled HoarderBug(Clone)(Clone) False
[Info   :RugbugRedfern.SkinwalkerMod] IsEnemyEnabled SpringMan(Clone)(Clone) False
[Info   :RugbugRedfern.SkinwalkerMod] IsEnemyEnabled Crawler(Clone)(Clone) False
[Info   :RugbugRedfern.SkinwalkerMod] IsEnemyEnabled PufferEnemy(Clone)(Clone) False
[Info   :RugbugRedfern.SkinwalkerMod] IsEnemyEnabled Flowerman(Clone)(Clone) False
[Info   :RugbugRedfern.SkinwalkerMod] IsEnemyEnabled Crawler(Clone)(Clone) False
[Info   :RugbugRedfern.SkinwalkerMod] IsEnemyEnabled HoarderBug(Clone)(Clone) False
[Info   :RugbugRedfern.SkinwalkerMod] IsEnemyEnabled DressGirl(Clone)(Clone) False
[Info   :RugbugRedfern.SkinwalkerMod] IsEnemyEnabled SandSpider(Clone)(Clone) False
[Info   :RugbugRedfern.SkinwalkerMod] IsEnemyEnabled Blob(Clone)(Clone) False
[Info   : Unity Log] clientRPC scrap values length: 1
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Info   : Unity Log] clientRPC scrap values length: 1
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Info   :ReservedItemSlotCore-1.8.12] 000
[Info   :ReservedItemSlotCore-1.8.12] 111
[Info   :ReservedItemSlotCore-1.8.12] RESULT: 0 222
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Info   : Unity Log] Current behaviour state: 1
[Info   : Unity Log] CHANGING BEHAVIOUR STATE!!! to 2
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Info   : Symbiosis] FOUND SPOT TO CHILL 0.4049039 UNITS AWAY FROM ME
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Info   : Symbiosis] FOUND SPOT TO CHILL 1.7841 UNITS AWAY FROM ME
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Info   : Unity Log] clientRPC scrap values length: 1
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Info   : Symbiosis] FOUND SPOT TO CHILL 0.4049039 UNITS AWAY FROM ME
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Info   : Symbiosis] FOUND SPOT TO CHILL 0.4049039 UNITS AWAY FROM ME
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Info   : Symbiosis] FOUND SPOT TO CHILL 0.2071723 UNITS AWAY FROM ME
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Info   :ReservedItemSlotCore-1.8.12] 000
[Info   :ReservedItemSlotCore-1.8.12] 111
[Info   :ReservedItemSlotCore-1.8.12] RESULT: 1 222
[Warning: Unity Log] PlayOneShot was called with a null AudioClip.
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Info   : Symbiosis] FOUND SPOT TO CHILL 2.188782 UNITS AWAY FROM ME
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Info   : Symbiosis] FOUND SPOT TO CHILL 0 UNITS AWAY FROM ME
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Info   : Unity Log] clientRPC scrap values length: 1
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Info   : Symbiosis] FOUND SPOT TO CHILL 1.660414 UNITS AWAY FROM ME
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Info   : Symbiosis] FOUND SPOT TO CHILL 1.660414 UNITS AWAY FROM ME
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Info   :RugbugRedfern.SkinwalkerMod] Got audio file paths (29)
[Info   : Unity Log] clip index: 4; current planet: 42-Auralis
[Info   : Unity Log] Current ship ambience clips length: 12
[Info   : Symbiosis] FOUND SPOT TO CHILL 0 UNITS AWAY FROM ME
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Info   :RugbugRedfern.SkinwalkerMod] Loaded clip from path C:/Program Files (x86)/Steam/steamapps/common/Lethal Company/Lethal Company_Data\..\Dissonance_Diagnostics\Output_39906e09-da51-45ba-8da4-44fe0fcec63a_950_133499956649231153.wav
[Info   :RugbugRedfern.SkinwalkerMod] Loaded clip from path C:/Program Files (x86)/Steam/steamapps/common/Lethal Company/Lethal Company_Data\..\Dissonance_Diagnostics\Output_320b9e8d-420b-4f79-bd94-df8fbc502800_738_133499956590785734.wav
[Info   :RugbugRedfern.SkinwalkerMod] Loaded clip from path C:/Program Files (x86)/Steam/steamapps/common/Lethal Company/Lethal Company_Data\..\Dissonance_Diagnostics\Output_39906e09-da51-45ba-8da4-44fe0fcec63a_951_133499956660816899.wav
[Info   :RugbugRedfern.SkinwalkerMod] Loaded clip from path C:/Program Files (x86)/Steam/steamapps/common/Lethal Company/Lethal Company_Data\..\Dissonance_Diagnostics\Output_320b9e8d-420b-4f79-bd94-df8fbc502800_739_133499956603565625.wav
[Info   :RugbugRedfern.SkinwalkerMod] Loaded clip from path C:/Program Files (x86)/Steam/steamapps/common/Lethal Company/Lethal Company_Data\..\Dissonance_Diagnostics\Output_6c6d90b6-db0e-4dbc-ab2b-823791b862c0_785_133499956636660406.wav
[Info   :RugbugRedfern.SkinwalkerMod] Loaded clip from path C:/Program Files (x86)/Steam/steamapps/common/Lethal Company/Lethal Company_Data\..\Dissonance_Diagnostics\Output_320b9e8d-420b-4f79-bd94-df8fbc502800_741_133499956616805489.wav
[Info   :RugbugRedfern.SkinwalkerMod] Loaded clip from path C:/Program Files (x86)/Steam/steamapps/common/Lethal Company/Lethal Company_Data\..\Dissonance_Diagnostics\Output_39906e09-da51-45ba-8da4-44fe0fcec63a_947_133499956596215691.wav
[Info   :RugbugRedfern.SkinwalkerMod] Loaded clip from path C:/Program Files (x86)/Steam/steamapps/common/Lethal Company/Lethal Company_Data\..\Dissonance_Diagnostics\Output_320b9e8d-420b-4f79-bd94-df8fbc502800_744_133499956669932148.wav
[Info   :RugbugRedfern.SkinwalkerMod] Loaded clip from path C:/Program Files (x86)/Steam/steamapps/common/Lethal Company/Lethal Company_Data\..\Dissonance_Diagnostics\Output_6c6d90b6-db0e-4dbc-ab2b-823791b862c0_784_133499956594895700.wav
[Info   :RugbugRedfern.SkinwalkerMod] Loaded clip from path C:/Program Files (x86)/Steam/steamapps/common/Lethal Company/Lethal Company_Data\..\Dissonance_Diagnostics\Output_39906e09-da51-45ba-8da4-44fe0fcec63a_949_133499956623485436.wav
[Info   :RugbugRedfern.SkinwalkerMod] Loaded clip from path C:/Program Files (x86)/Steam/steamapps/common/Lethal Company/Lethal Company_Data\..\Dissonance_Diagnostics\Output_39906e09-da51-45ba-8da4-44fe0fcec63a_948_133499956607875581.wav
[Info   :RugbugRedfern.SkinwalkerMod] Loaded clip from path C:/Program Files (x86)/Steam/steamapps/common/Lethal Company/Lethal Company_Data\..\Dissonance_Diagnostics\Output_6c6d90b6-db0e-4dbc-ab2b-823791b862c0_786_133499956647101174.wav
[Info   :RugbugRedfern.SkinwalkerMod] Loaded clip from path C:/Program Files (x86)/Steam/steamapps/common/Lethal Company/Lethal Company_Data\..\Dissonance_Diagnostics\Output_39906e09-da51-45ba-8da4-44fe0fcec63a_952_133499956665767074.wav
[Info   :RugbugRedfern.SkinwalkerMod] Loaded clip from path C:/Program Files (x86)/Steam/steamapps/common/Lethal Company/Lethal Company_Data\..\Dissonance_Diagnostics\Output_320b9e8d-420b-4f79-bd94-df8fbc502800_743_133499956654051604.wav
[Info   :RugbugRedfern.SkinwalkerMod] Loaded clip from path C:/Program Files (x86)/Steam/steamapps/common/Lethal Company/Lethal Company_Data\..\Dissonance_Diagnostics\Output_320b9e8d-420b-4f79-bd94-df8fbc502800_742_133499956624095427.wav
[Info   :RugbugRedfern.SkinwalkerMod] Loaded clip from path C:/Program Files (x86)/Steam/steamapps/common/Lethal Company/Lethal Company_Data\..\Dissonance_Diagnostics\Output_320b9e8d-420b-4f79-bd94-df8fbc502800_740_133499956606385598.wav
[Info   :RugbugRedfern.SkinwalkerMod] Loaded clip from path C:/Program Files (x86)/Steam/steamapps/common/Lethal Company/Lethal Company_Data\..\Dissonance_Diagnostics\Output_6c6d90b6-db0e-4dbc-ab2b-823791b862c0_787_133499956657491810.wav
[Info   :RugbugRedfern.SkinwalkerMod] Loaded clip from path C:/Program Files (x86)/Steam/steamapps/common/Lethal Company/Lethal Company_Data\..\Dissonance_Diagnostics\Output_dab4c718-4ff6-4a05-98b0-3b50bafe5d93_1596_133499956598875678.wav
[Info   :RugbugRedfern.SkinwalkerMod] Loaded clip from path C:/Program Files (x86)/Steam/steamapps/common/Lethal Company/Lethal Company_Data\..\Dissonance_Diagnostics\Output_dab4c718-4ff6-4a05-98b0-3b50bafe5d93_1598_133499956629465378.wav
[Info   :RugbugRedfern.SkinwalkerMod] Loaded clip from path C:/Program Files (x86)/Steam/steamapps/common/Lethal Company/Lethal Company_Data\..\Dissonance_Diagnostics\Output_dab4c718-4ff6-4a05-98b0-3b50bafe5d93_1599_133499956643420775.wav
[Info   :RugbugRedfern.SkinwalkerMod] Loaded clip from path C:/Program Files (x86)/Steam/steamapps/common/Lethal Company/Lethal Company_Data\..\Dissonance_Diagnostics\Output_dab4c718-4ff6-4a05-98b0-3b50bafe5d93_1600_133499956649541143.wav
[Info   :RugbugRedfern.SkinwalkerMod] Loaded clip from path C:/Program Files (x86)/Steam/steamapps/common/Lethal Company/Lethal Company_Data\..\Dissonance_Diagnostics\Output_dab4c718-4ff6-4a05-98b0-3b50bafe5d93_1601_133499956656681809.wav
[Info   :RugbugRedfern.SkinwalkerMod] Loaded clip from path C:/Program Files (x86)/Steam/steamapps/common/Lethal Company/Lethal Company_Data\..\Dissonance_Diagnostics\Output_dab4c718-4ff6-4a05-98b0-3b50bafe5d93_1597_133499956623235428.wav
[Info   :RugbugRedfern.SkinwalkerMod] Loaded clip from path C:/Program Files (x86)/Steam/steamapps/common/Lethal Company/Lethal Company_Data\..\Dissonance_Diagnostics\Output_dab4c718-4ff6-4a05-98b0-3b50bafe5d93_1602_133499956661981992.wav
[Info   :RugbugRedfern.SkinwalkerMod] Loaded clip from path C:/Program Files (x86)/Steam/steamapps/common/Lethal Company/Lethal Company_Data\..\Dissonance_Diagnostics\Output_dab4c718-4ff6-4a05-98b0-3b50bafe5d93_1604_133499956672272306.wav
[Info   :RugbugRedfern.SkinwalkerMod] Loaded clip from path C:/Program Files (x86)/Steam/steamapps/common/Lethal Company/Lethal Company_Data\..\Dissonance_Diagnostics\Output_dab4c718-4ff6-4a05-98b0-3b50bafe5d93_1603_133499956668082163.wav
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Info   : Symbiosis] FOUND SPOT TO CHILL 0 UNITS AWAY FROM ME
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Info   : Unity Log] clientRPC scrap values length: 1
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Info   :ReservedItemSlotCore-1.8.12] 000
[Info   :ReservedItemSlotCore-1.8.12] 111
[Info   :ReservedItemSlotCore-1.8.12] RESULT: 0 222
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Info   : Symbiosis] FOUND SPOT TO CHILL 0 UNITS AWAY FROM ME
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Info   :ReservedItemSlotCore-1.8.12] 000
[Info   :ReservedItemSlotCore-1.8.12] 111
[Info   :ReservedItemSlotCore-1.8.12] RESULT: 2 222
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Info   : Symbiosis] FOUND SPOT TO CHILL 0 UNITS AWAY FROM ME
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Some metrics in the collection went over the configured values limit. Some values were ignored.
[Info   :ReservedItemSlotCore-1.8.12] 000
[Info   :ReservedItemSlotCore-1.8.12] 111
[Info   :ReservedItemSlotCore-1.8.12] RESULT: 1 222
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Info   : Symbiosis] FOUND SPOT TO CHILL 0 UNITS AWAY FROM ME
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[Info   :RugbugRedfern.SkinwalkerMod] IsEnemyEnabled ForestGiant(Clone) False
[Info   :RugbugRedfern.SkinwalkerMod] IsEnemyEnabled ForestGiant(Clone) False
[Info   :RugbugRedfern.SkinwalkerMod] IsEnemyEnabled HoarderBug(Clone)(Clone) False
[Info   :RugbugRedfern.SkinwalkerMod] IsEnemyEnabled Centipede(Clone)(Clone) False
[Info   :RugbugRedfern.SkinwalkerMod] IsEnemyEnabled ForestGiant(Clone) False
[Info   :RugbugRedfern.SkinwalkerMod] IsEnemyEnabled BaboonHawkEnemy(Clone) False
[Info   :RugbugRedfern.SkinwalkerMod] IsEnemyEnabled HoarderBug(Clone)(Clone) False
[Info   :RugbugRedfern.SkinwalkerMod] IsEnemyEnabled SpringMan(Clone)(Clone) False
[Info   :RugbugRedfern.SkinwalkerMod] IsEnemyEnabled Crawler(Clone)(Clone) False
[Info   :RugbugRedfern.SkinwalkerMod] IsEnemyEnabled PufferEnemy(Clone)(Clone) False
[Info   :RugbugRedfern.SkinwalkerMod] IsEnemyEnabled Flowerman(Clone)(Clone) False
[Info   :RugbugRedfern.SkinwalkerMod] IsEnemyEnabled Crawler(Clone)(Clone) False
[Info   :RugbugRedfern.SkinwalkerMod] IsEnemyEnabled HoarderBug(Clone)(Clone) False
[Info   :RugbugRedfern.SkinwalkerMod] IsEnemyEnabled DressGirl(Clone)(Clone) False
[Info   :RugbugRedfern.SkinwalkerMod] IsEnemyEnabled SandSpider(Clone)(Clone) False
[Info   :RugbugRedfern.SkinwalkerMod] IsEnemyEnabled Blob(Clone)(Clone) False
[Info   : Symbiosis] FOUND SPOT TO CHILL 0 UNITS AWAY FROM ME
[Warning: Unity Log] Particle System is trying to spawn on a mesh with zero surface area
[

**Comment by AudioKnight** [comment]
In testing Auralis on both stormy and eclipsed (just in case), I wasn't able to reproduce this warning message. It might be one of your other mods.
