### ISSUE TITLE
Jetpack ceiling is wayyy to low

### ISSUE THREAD

**Issue by ArsenicBismuth** [AudioKnight/Starlancer#12]
This map size promotes jetpack usage, but strangely the ceiling is wayyy to low (after certain height it just explodes). Other maps have almost unlimited height (at least, enought to see the map as a small square).

**Comment by AudioKnight** [comment]
Weird. I don't even know where to begin with changing that, but I'll look into it.

**Comment by ArsenicBismuth** [comment]
Wait nvm, doesn't seem to be a real issue. I guess some of my mod is updated when I play now? coz last I tried was 2 days ago. Or I was unknowingly holding the throttle too long as the scale of the map is larger than others (thus messing with my frame of reference).

Sorry for the trouble!
