### ISSUE TITLE
Unable to use custom dungeons

### ISSUE THREAD

**Issue by KitsuneNoNatsu** [AudioKnight/Starlancer#13]
Been hunting for some good moon mods for a personal modpack, paired with some nice interior mods, I was however unable to get your moons to work with them, the modpack and configs are 018d8579-9ad0-cab4-64e3-5f30ce69ee1c
If you can figure out what's going wrong, please let me know

**Comment by AudioKnight** [comment]
Lethal Expansion can suffer from incompatibilities with Lethal Level Loader, try adding this mod and let me know if it works.
https://thunderstore.io/c/lethal-company/p/jockie/LethalExpansionCore/

If that doesn't work, try setting "list" to "all" instead here. You've got the other interior mod set correctly, but it's possible the difference here might cause an issue.
![image](https://github.com/AudioKnight/Starlancer/assets/153391827/c7667466-7928-4daf-891a-5f7934190b66)

**Comment by KitsuneNoNatsu** [comment]
Well, Auralis seems to work, but now Triskelion doesn't, even after deleting every config and ONLY having StarlancerMoons enables

**Comment by AudioKnight** [comment]
Is it Scoopy's interiors that's throwing the Triskelion error in this case? For some reason it doesn't seem to accept Triskelion even though it's setup the same way that Auralis is, and neither I nor the LLL dev know why that is

**Comment by KitsuneNoNatsu** [comment]
Well, hard to say, as my console hasn't been opening up for the last couple days, I'll give it a test though

**Comment by KitsuneNoNatsu** [comment]
That would be a no, it's stuck on "Random Seed: "
![Screenshot_20240209_194842](https://github.com/AudioKnight/Starlancer/assets/84426602/851377c6-340e-466b-9552-d8a787b1d0ca)

**Comment by AudioKnight** [comment]
Triskelion is unfortunately broken as of LLL 1.1.x and I can't figure out why.

I'm currently trying to fix it, but I have no idea when this issue will be resolved. Since I made some other fixes for Auralis, I'm going to push a new update with Triskelion locked away. It'll still be playable if you'd prefer to stick with the previous versions of Starlancer and LLL.

**Comment by AudioKnight** [comment]
@KitsuneNoNatsu I've uploaded a new version of StarlancerMoons that I've successfully tested on its own. Please give it a try and let me know if you encounter any issues :)
