### ISSUE TITLE
Lighting issue and door?

### ISSUE THREAD

**Issue by VioletXe** [AudioKnight/Starlancer#15]
The fire exits seem to be the same but I remember the door being... different. Am I crazy?
![20240210032449_1](https://github.com/AudioKnight/Starlancer/assets/157070685/bbd30564-be26-4745-b4c5-9e1c5a953dfd)

**Comment by VioletXe** [comment]
Follow up, Auralis also seems to have really weird lightning now. I can walk arond without a flashlight just fine.
![20240210034821_1](https://github.com/AudioKnight/Starlancer/assets/157070685/882ff435-da63-4aac-a707-cc9cb64cfac9)
![20240210034829_1](https://github.com/AudioKnight/Starlancer/assets/157070685/4b2d40e5-fc31-41f5-95f5-3e5dd450d0df)
Doors also seem to take to lightning more intensely than other props since they light up down hallways. They've visibly more illuminated that everything else.

**Comment by AudioKnight** [comment]
I did actually change the door model to the base game style to make it 100% clear "this is the main entrance", so you're not crazy there 🤭

I haven't gotten any other reports of that lighting issue, but I'll take a look in a bit
