### ISSUE TITLE
Crashes on new auralis & solace

### ISSUE THREAD

**Issue by Slydylan** [AudioKnight/Starlancer#19]
Triskelion seemed to work fine. Auralis & Solace both brick my laptop. Like literally turns my machine off with no warning (meaning i hit my temp limit)
Can't find any errors or anything. It started with Solace on the first update where solace was put in. Then, update after that, Auralis AND Solace are crashing my computer.
I have an rx 6800s and a ryzen 9 6800HS. This is not a new issue for me, but it's consistent with your map. I can load other maps without a problem, regardless of Dungeon size.
It's probably an issue with AMDs drivers and unity but there's got to be some inconsistency between this map and others since I can run the game no problem on other maps..

**Comment by AudioKnight** [comment]
That's super weird. I put out a performance update last night, have you tried that yet?

**Comment by Slydylan** [comment]
I did and Auralis & Solace loaded fine first try gave me 70 fps but Triskelion bricked my machine.

**Comment by Slydylan** [comment]
third try auralis with a smaller dungeon also did the same and im pretty sure i can corrupt my whole machine doing this so thats it for me...

**Comment by AudioKnight** [comment]
I'm sorry to hear that. Other than the dungeon size tweaks I don't know what the cause could be. I totally understand if you don't want to risk it any further, but I just pushed another update that has even more performance gains.

**Comment by Slydylan** [comment]
the game uses HDRP and game engines notoriously have discrepancies in rendering methods which heavily impact performance from brand to brand. not sure what it could be in specific but HDRP is known for being very demanding on all systems even the best

**Comment by Slydylan** [comment]
no change for me in the update i crashed first try

**Comment by Slydylan** [comment]
i have hd lethal company but i almost never crash just from that. this has been consistently just your moon and not other custom moons. im also using the forked version of LLL with fixes and AC compatibility

**Comment by AudioKnight** [comment]
Well I hope at some point it resolves itself for you, I've never had my moons crash my OC, so unfortunately there's nothing more to be done unless I happen to inadvertently fix whatever's causing your problem

**Comment by Slydylan** [comment]
it is probably a rendering overload that occurs more so with amd and asus drivers when being used in unity games as amd users get crashes in unity games often
