### ISSUE TITLE
Navmesh issue

### ISSUE THREAD

**Issue by sfDesat** [AudioKnight/Starlancer#2]
I think your map is very promising, but i found some issues while playing it. A big one was this:
![image](https://github.com/AudioKnight/Starlancer/assets/75356901/be96f6c8-c179-4ea3-b968-59feab3ed9b9)
Your navmesh not working or not existing.

**Comment by AudioKnight** [comment]
Thanks! I think I forgot to bake the navmesh after I removed the default one or some such. I'm still learning how Unity and the SDK interact, but I'll look into it once I'm back from my current trip.

Also part of my drive to release my mod came from seeing your moons, so I really appreciate you checking my mod out!

**Comment by sfDesat** [comment]
That's great to hear. Let me know if you run into any issue you can't figure out.
