### ISSUE TITLE
Solace delivery ship lacks music and entities spawn incorrectly

### ISSUE THREAD

**Issue by Pyromaniax** [AudioKnight/Starlancer#20]
Other than the delivery ship lacking music i noticed inside enemies spawning outside, namely spore lizards

**Comment by AudioKnight** [comment]
Just pushed a new update in which the ItemShip music is fixed.

Spore lizards are intentional. I'm leveraging my own StarlancerAIFix to allow inside enemies to behave normally when spawned outside :)

**Comment by Pyromaniax** [comment]
Thanks for the update, any chance you can make a option for the inside enemies outside to be disabled in a config?

**Comment by AudioKnight** [comment]
You can manipulate spawn lists in the LLL config, and since it auto-generates a config for my mod, I won't be adding a separate config for my moon in the foreseeable future.

**Comment by Pyromaniax** [comment]
would you mind telling me how can i find that file? Can't seem to locate it in the config folder even with the lethal config mod
