### ISSUE TITLE
Enemy and Collision Issues

### ISSUE THREAD

**Issue by Kayden21** [AudioKnight/Starlancer#3]
Hey great mod so far and I know its early in so you probably know about some of these problems but I figured I would say it just in case. Most enemies if not all on the outside just dont really function they all get stuck in place which you probably know about already. The collision on the ship landing pad seems to let items just fall through sometimes like we just dropped the mask item in front of the ship and it was gone through the floor.

**Comment by AudioKnight** [comment]
Thanks for letting me know! I'll work on addressing the issues soon, I'm just away from the computer for a bit
