### ISSUE TITLE
[Feature] Masked pathing towards ship 

### ISSUE THREAD

**Issue by MathiusXII** [AudioKnight/Starlancer#30]
Masked have that cool ability where they can hide by the lever inside the ship, but I've never seen it happen naturally. Even after spawning them near the ship it's hard to get them to do it.

It seems like if they just happen to get near the ship while no one is around they'll do it, but they never path to it on their own.

It'd be cool if while outside they would have a chance to start walking and running straight towards the ship (unless a player gets close) and hide inside.

Might be better as a separate mod, idk.

**Comment by AudioKnight** [comment]
That'd be better as a separate mod, I don't want to add extra functionality to enemies, especially ones that aren't actually affected by my mod directly.
