### ISSUE TITLE
[Feature] Snare Flea outdoors AI

### ISSUE THREAD

**Issue by MathiusXII** [AudioKnight/Starlancer#34]
Currently when fleas go outside they just wander around aimlessly. (I assume hopelessly looking for a place to attach to the ceiling)

Could you make it where while they're outside they go into chase mode if they see someone and wander if no one's near?

Attaching sideways to trees or the ship or whatever would be cool, but idk how hard that'd be. Maybe sneaking inside the ship and attaching to its ceiling?

**Comment by AudioKnight** [comment]
I'll consider the chasing/wandering, but changing the clinging direction would be more than I'm willing to allocate time for, and pathing it to the ship would also be added functionality that I believe lies outside the scope of the mod (plus would be considered unfair by a lot of people and I don't have the energy to deal with that lol).

Other people are welcome to make a mod that does that, and I wouldn't feel like my toes were being stepped on or anything. They'll likely want to have it with SLAIFix/SEE as a dependency, of course.
