### ISSUE TITLE
[BUG] Masked Enemy

### ISSUE THREAD

**Issue by MPRATCH-V2** [AudioKnight/Starlancer#35]
This mod seems to cause the masked enemy to repeatedly leave and re-enter the facility. The config also lacks a masked enemy section which could've been sued as a workaround for people while waiting for an update.

**Comment by AudioKnight** [comment]
Enemy Escape doesn't touch Masked Enemies, since they already have the functionality to enter and leave. I know this is a bit late, but I hope you figured out a different solution to the issue.

**Comment by MPRATCH-V2** [comment]
> Enemy Escape doesn't touch Masked Enemies, since they already have the functionality to enter and leave. I know this is a bit late, but I hope you figured out a different solution to the issue.

I paused working on my modpack until v55 drops but from what I remember it was an ongoing issue. I will make a clean modpack in the next day or two with only imperium and starlance escape installed to verify the origin. I'll link logs if the issue persists.

**Comment by MPRATCH-V2** [comment]
I'm a little late but I did test and was incorrect about this "issue" being caused by starlancer escape. During my testing I was always invisible so that the masked would pathfind instead of target me. This apparently causes masked to repeatedly enter and exit the facility presumably looking for a target. Essentially this is perfectly normal vanilla behavior. I'd still like to request a config option to modify the masked escape chance but seeing as your mod currently doesn't touch them at all I understand if you don't want to add in functionality to change their spawns.
