### ISSUE TITLE
Uncompatible with Backrooms mod

### ISSUE THREAD

**Issue by Zuploader** [AudioKnight/Starlancer#4]
If you are using backrooms mods, when you enter the dungeon you are blocked in between the backroom level and the real dungeons interiors, they merged together. i think maybe it's because you put the real dungeon too low, like at the same height than where the backrooms level is (usually very deep under the real dungeon on any other moon)

**Comment by AudioKnight** [comment]
Thanks for the heads up! You're 100% right, I lowered it earlier in an attempt to fix weather sounds occurring in the interior, then forgot to move it back once I found out the actual fix.

This will be fixed in the next release.

**Comment by AudioKnight** [comment]
This incompatibility should be resolved now, please let me know if otherwise.
