### ISSUE TITLE
Hidden Planet

### ISSUE THREAD

**Issue by Xliecc** [AudioKnight/Starlancer#44]
Can you tell me how to route to the hidden planet？ I can't find it

**Comment by free7iu** [comment]
Heard my friend say it takes 16 rounds to get to the hidden planet.Why can't we go?

**Comment by AudioKnight** [comment]
Sorry, haven't been checking GitHub lately ^^;

The hidden moon has a secret route word, with the letters scattered around my 3 non-hidden moons: Solace, Triskelion, and Auralis. If you visit the shack on Auralis, you'll find a note, and I'll start you off by saying there's also a symbol inside the shack.

**Comment by free7iu** [comment]
How many letters are there on this planet? I only found six

**Comment by free7iu** [comment]
okay, I think I got a name. Thanks！

**Comment by AudioKnight** [comment]
Gonna close the thread, but just wanted to let you know that there's 7 symbols in total :)
