### ISSUE TITLE
Performance Optimization

### ISSUE THREAD

**Issue by sfDesat** [AudioKnight/Starlancer#5]
I think the map is very promising. I am keeping up with your development and I noticed that there is some optimizations to be made. (The game is by default already poorly optimized) So I thought I make a list of things you can do to optimize your map:
- I recommend making the trees static if they don't have an animation. Same goes for the every object in your scene. Just select the prefab in the Assetbrowser or the assets in the Scene Hierarchy and click in the top-right on static.
- Second things is that you can adjust the shadows i.e. change the resolution or the cut away. You can do this in your Scene Hierarchy > Lighting > Sky and Fog Global Volume. Then under shadows there are a bunch of options you can mess with.
- You can also think about adding a distant fog. This is really up to how you want your map to look. Fog can hide the distant cutout that the camera has in the vanilla game and improve performance. This is up to you.
- LOD's are Level Of Detail. This is a bit harder to implement and requires some changes to models or extra models, but can greatly improve performance. [Here is the unity documentation](https://docs.unity3d.com/Manual/LevelOfDetail.html).

There are probably other things you can do for performance, but those are more difficult and probably require coding. I thought you might want to know some of the ways I learned to optimize my moons. You can always ask HolographicWings for more tips if he has any (He is the developer behind Lethal Expansion). I recommend messing about with things. You can also add post processing in the Sky and Fog Global Volume.

**Comment by AudioKnight** [comment]
Thank you very much for the tips! It really lifts me up to see how many people have been checking out/keeping up with my mod :)

I'm currently adjusting some things, so I'll try out those performance optimizations in the next patch!

**Comment by AudioKnight** [comment]
> * You can also think about adding a distant fog. This is really up to how you want your map to look. Fog can hide the distant cutout that the camera has in the vanilla game and improve performance. This is up to you.

How would I go about doing this? And would this essentially cull everything behind it to improve performance?

**Comment by sfDesat** [comment]
> > * You can also think about adding a distant fog. This is really up to how you want your map to look. Fog can hide the distant cutout that the camera has in the vanilla game and improve performance. This is up to you.
> 
> How would I go about doing this? And would this essentially cull everything behind it to improve performance?

I don't think it actually culls anything behind it. I think that would be something you would have to do manually on the camera (There is no access to the camera in the SDK, as far as I know). It is more a visual thing, but you could look it up. Under the Sun asset in the Scene Hierarchy there are 2 types of fog: the Global Volume (This is a global effect) and the LocalVolumetricFog (This is a local effect, only inside an specific area).

**Comment by AudioKnight** [comment]
Gotcha. I've actually messed around quite a bit with the fog, but I do wanna see if I can get it to emulate a distance fog. Thanks again :)

**Comment by AudioKnight** [comment]
@sfDesat I don't know if you're on the modding discord, so I just wanted to let you know that I've updated the mod and rearranged things into a modpack, just in case you wanted to swap Starlancer for StarlancerMoons in Explorations.

**Comment by sfDesat** [comment]
Yeah, I think I am going to swap them.
