### ISSUE TITLE
World needs some optimizing

### ISSUE THREAD

**Issue by YuroKashine** [AudioKnight/Starlancer#6]
First thing... amazing map. For how empty it still is, its really beautiful.

However maybe the giants should spawn later and maybe not as many. there already is a masked guy that spawns immediately when u land and multiple dogs spawn early game. there are 3 giants spawning at the same time at the exact same location. it would be better if they spawn further in the trees and later in the evening... maybe 1 giant too since its a really open map still.

Oh and it would be really cool to add like a bunker with a fire exit somewhere in the forest close to the ship.

And maybe you can add like an ice lake fishing hut with a fire exit.

**Comment by AudioKnight** [comment]
Thanks for the suggestions!

Just to check, are you using any sort of mod that increases spawn rates? It is set for dangerous spawns, but I haven't noticed anything as severe as what you're describing outside. I might tone down the interior spawn rate though.

**Comment by YuroKashine** [comment]
Not sure anything screws with the spawn rates. I use 68 mods but none as far as i know that changes spawnrates. Havent seen anything in the config files about spawnrates either. Maybe brutal company manus but i believe that just spawns in other mobs during events but not giants. If u want i can send u the code to my modprofile of the thunderstore mod manager and u can check it for yourself. Im already glad u fixed the big where all the monsters outside were frozen... including the masked guy when he exited... making him always kill u when u go in and out haha. Great job on that fix!

I noticed i also get a lot of audio bugs on this map too but that might be due to another mod... not sure😂 i guess the game update doesnt help either with mods haha.

**Comment by AudioKnight** [comment]
In my experience Brutal Company raises spawn rates globally, so please test out Auralis without and see if it's more reasonable please :)

**Comment by YuroKashine** [comment]
Well it seems to work normally now but there are still a lot of mobs spawning.
Also im having a really heavy audio bug on this map but i have no clue where it might be coming from.

Theres a picture in the attachments that shows the amount of mobs spawning like around 3pm already.

Also here is the code to my thunderstore modpack. i have no clue what is happening with the audio.
018cff2e-65e3-9425-28ec-76e697e67ba2

![high spawns](https://github.com/AudioKnight/Starlancer/assets/156379068/17bcb7ca-be84-4db0-8973-33baf5fdbf9a)

**Comment by AudioKnight** [comment]
By 3PM that actually looks about right, but I might tone down the mask spawn just a bit.

Can you describe the audio bug for me?

**Comment by YuroKashine** [comment]
The moment i step out of the ship i just dont hear any footsteps or items... audio gets bugged a lot. Yeah mostly that kind of thing. The only thing i accurately hear every time is the beep from scanning haha.

Like even when the masks are running towards me i mayne hear 10% of all their running steps.

**Comment by AudioKnight** [comment]
I just loaded it up and everything seems normal, I'm hearing footsteps just fine. I took a look at your modlist:
![image](https://github.com/AudioKnight/Starlancer/assets/153391827/917ce33a-97ab-4796-9fd7-f144bd2a02cb)

It's possible that you have some kind of custom sound interfering with footstep audio files, the only thing I've done is tag the terrain and walkways to use vanilla footstep sounds.

If you don't mind, I'd like for you to try it with just Starlancer loaded and see if the issue persists. If it does, please post the bepinex log showing whatever errors it's throwing.

**Comment by YuroKashine** [comment]
Hey Thank you for looking into it.

You are actually right, after i turned it off i did have audible footsteps again. and that audio bug seemed to have gone away. However every 1 in 8 steps were silent but im not sure if thats also so in vanilla XD at least this is playable again. Thank u for looking into it.

I cant wait for you to tweak some things and add more things to the mod, i love how this moon looks.

Please do decrease the mask guys a little and maybe spawn the giant a little later and also with a lower spawnweight. we did a test run today and again i got like 3 giants and 4 dogs around 2pm which were constantly camping the ship. 

the dogs arent to bad because you can dodge them and if youre quiet enough u can circle around them. the giants however have a massive vision range in such an open map so they will camp you and kill you making u unable to do anything really hahaha

**Comment by AudioKnight** [comment]
> You are actually right, after i turned it off i did have audible footsteps again. and that audio bug seemed to have gone away. However every 1 in 8 steps were silent but im not sure if thats also so in vanilla XD at least this is playable again. Thank u for looking into it.

I was playing with some friends last night and also have the issue of footsteps sort of disappearing after a bit, but I'm trying another fix for it.

> I cant wait for you to tweak some things and add more things to the mod, i love how this moon looks.

Thank you! :)

> Please do decrease the mask guys a little and maybe spawn the giant a little later and also with a lower spawnweight. we did a test run today and again i got like 3 giants and 4 dogs around 2pm which were constantly camping the ship.
> 
> the dogs arent to bad because you can dodge them and if youre quiet enough u can circle around them. the giants however have a massive vision range in such an open map so they will camp you and kill you making u unable to do anything really hahaha

I've lowered the weighting for Masked Employees (though I can't modify the cap for them). I'm lowering the outside cap and slowed down the initial spawns, but 3 giants will probably always spawn eventually, just for how I'm theming the moon, but I'll leave room for just 2 dogs to spawn. On the plus side, I'm adding a small structure at the halfway point that should allow you to hide from the giants :)

New version will hopefully be out in a few hours, running some tests right now.

**Comment by AudioKnight** [comment]
@YuroKashine just in case you haven't seen, I've updated the mod to 0.2.0 (along with changing the main mod to a modpack), so I hope you enjoy!

**Comment by YuroKashine** [comment]
Hey thanks! i just saw it yeah, i been busy changing things in my modpack and sadly i cant export my pack as a code anymore since yesterday, it seems thunderstore is broken. Im waiting untill it is fixed so i can test with my buddy again and ill be sure to check out auralis! ill let u know!

**Comment by YuroKashine** [comment]
Ehm,

Which what does what? why are there 2 now?
![image](https://github.com/AudioKnight/Starlancer/assets/156379068/a4eb98b9-53ad-4cc9-962a-f882deb060fe)

**Comment by AudioKnight** [comment]
Starlancer is the modpack that will end up holding more Starlancer mods as I release them.

StarlancerMoons is the first of the mods for the pack, it will contain all of my moons (and tilesets once I make them).

**Comment by YuroKashine** [comment]
Oh okay so starlancer is an empty mod now or did you add stuff there already? do i need that for the mood? hahaha

**Comment by AudioKnight** [comment]
"Starlancer" is an empty mod that will consolidate the moon mod and all future Starlancer mods. You don't need it if you're only interested in new moons/tilesets, but I'll be adding other mods with different content down the line.

To reiterate: StarlancerMoons has no dependency on Starlancer. Starlancer is just going to be a modpack.

**Comment by Qugar** [comment]
Could you reactivate the early spawns outside on Auralis or at least make them optionally switchable via a config?

I understand that many people didn't like this and that it was just a mistake, but we loved that Auralis spawned monsters so early because it was something unique.

**Comment by AudioKnight** [comment]
I'll try to find a sweet spot :)

**Comment by Qugar** [comment]
I've now tested the changes a bit.

First of all we love it but to be fair I have to say if it is possible it might be nicer for other players if the first outside enemies would spawn at 9 am, I think that could be a sweet spot that everyone can live with.

Thanks so far we are happy, great mod :+1:
