### ISSUE TITLE
Error Message after leaving the Moon

### ISSUE THREAD

**Issue by VanilaBOI** [AudioKnight/Starlancer#8]
[Error  : Unity Log] ArgumentNullException: String reference not set to an instance of a String.
Parameter name: s
Stack trace:
System.Text.Encoding.GetBytes (System.String s) (at <787acc3c9a4c471ba7d971300105af24>:IL_0012)
Unity.Netcode.CustomMessagingManager.UnregisterNamedMessageHandler (System.String name) (at <895801699cfc4b4ab52267f31e2a4998>:IL_0000)
Unity.Netcode.Components.NetworkTransform.OnNetworkDespawn () (at <8405014387374c19a6350f43289ea251>:IL_0025)
Unity.Netcode.NetworkBehaviour.InternalOnNetworkDespawn () (at <895801699cfc4b4ab52267f31e2a4998>:IL_000D)
UnityEngine.Debug:LogException(Exception)
Unity.Netcode.NetworkBehaviour:InternalOnNetworkDespawn()
Unity.Netcode.NetworkObject:InvokeBehaviourNetworkDespawn()
Unity.Netcode.NetworkSpawnManager:OnDespawnObject(NetworkObject, Boolean)
Unity.Netcode.NetworkSpawnManager:DespawnObject(NetworkObject, Boolean)
Unity.Netcode.NetworkObject:Despawn(Boolean)
Unity.Netcode.DefaultSceneManagerHandler:MoveObjectsFromSceneToDontDestroyOnLoad(NetworkManager&, Scene)
Unity.Netcode.NetworkSceneManager:UnloadScene(Scene)
<unloadSceneForAllPlayers>d__254:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

[Error  : Unity Log] ArgumentNullException: String reference not set to an instance of a String.
Parameter name: s
Stack trace:
System.Text.Encoding.GetBytes (System.String s) (at <787acc3c9a4c471ba7d971300105af24>:IL_0012)
Unity.Netcode.CustomMessagingManager.UnregisterNamedMessageHandler (System.String name) (at <895801699cfc4b4ab52267f31e2a4998>:IL_0000)
Unity.Netcode.Components.NetworkTransform.OnNetworkDespawn () (at <8405014387374c19a6350f43289ea251>:IL_0025)
Unity.Netcode.NetworkBehaviour.InternalOnNetworkDespawn () (at <895801699cfc4b4ab52267f31e2a4998>:IL_000D)
UnityEngine.Debug:LogException(Exception)
Unity.Netcode.NetworkBehaviour:InternalOnNetworkDespawn()
Unity.Netcode.NetworkObject:InvokeBehaviourNetworkDespawn()
Unity.Netcode.NetworkSpawnManager:OnDespawnObject(NetworkObject, Boolean)
Unity.Netcode.NetworkSpawnManager:DespawnObject(NetworkObject, Boolean)
Unity.Netcode.NetworkObject:Despawn(Boolean)
Unity.Netcode.DefaultSceneManagerHandler:MoveObjectsFromSceneToDontDestroyOnLoad(NetworkManager&, Scene)
Unity.Netcode.NetworkSceneManager:UnloadScene(Scene)
<unloadSceneForAllPlayers>d__254:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

[Error  : Unity Log] ArgumentNullException: String reference not set to an instance of a String.
Parameter name: s
Stack trace:
System.Text.Encoding.GetBytes (System.String s) (at <787acc3c9a4c471ba7d971300105af24>:IL_0012)
Unity.Netcode.CustomMessagingManager.UnregisterNamedMessageHandler (System.String name) (at <895801699cfc4b4ab52267f31e2a4998>:IL_0000)
Unity.Netcode.Components.NetworkTransform.OnNetworkDespawn () (at <8405014387374c19a6350f43289ea251>:IL_0025)
Unity.Netcode.NetworkBehaviour.InternalOnNetworkDespawn () (at <895801699cfc4b4ab52267f31e2a4998>:IL_000D)
UnityEngine.Debug:LogException(Exception)
Unity.Netcode.NetworkBehaviour:InternalOnNetworkDespawn()
Unity.Netcode.NetworkObject:InvokeBehaviourNetworkDespawn()
Unity.Netcode.NetworkSpawnManager:OnDespawnObject(NetworkObject, Boolean)
Unity.Netcode.NetworkSpawnManager:DespawnObject(NetworkObject, Boolean)
Unity.Netcode.NetworkObject:Despawn(Boolean)
Unity.Netcode.DefaultSceneManagerHandler:MoveObjectsFromSceneToDontDestroyOnLoad(NetworkManager&, Scene)
Unity.Netcode.NetworkSceneManager:UnloadScene(Scene)
<unloadSceneForAllPlayers>d__254:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

**Comment by AudioKnight** [comment]
Hello.

I tested by landing on Auralis multiple times and I was able to replicate this error, but it doesn't seem like it actually affects anything. Unless something fatal happens and is logged, I'd say this is more than likely an issue with the SDK I built the moon in and it can probably be ignored.
